site_name: CRIPT Python SDK

repo_url: https://github.com/C-Accel-CRIPT/cript
repo_name: C-Accel-CRIPT/cript

theme:
  name: material
  logo: assets/images/CRIPT_full_logo_colored_transparent.png
  favicon: assets/images/favicon.ico
  icon:
    admonition:
      alert: octicons/alert-16
  features:
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# This links the CRIPT logo to the CRIPT homepage
extra:
  homepage: https://criptapp.org

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_bases: false
            show_source: false
            docstring_style: google

nav:
  - Home: index.md
  - Quick Start: quickstart.md  
  - Tutorials:
    - Full Tutorial: tutorials/full_tutorial.md
    - Installation: tutorials/installation.md
    - Getting an API Token: tutorials/api_token.md
    - Simulation: tutorials/simulation.md
    - Synthesis: tutorials/synthesis.md
  - Nodes:
      - All: nodes/all.md
      - Collection: nodes/collection.md
      - Computation: nodes/computation.md
      - Computational Process: nodes/computational_process.md
      - Data: nodes/data.md
      - Experiment: nodes/experiment.md
      - File: nodes/file.md
      - Group: nodes/group.md
      - Inventory: nodes/inventory.md
      - Material: nodes/material.md
      - Project: nodes/project.md
      - Process: nodes/process.md
      - Reference: nodes/reference.md
      - Software: nodes/software.md
      - User: nodes/user.md
  - Sub-objects:
      - All: subobjects/all.md
      - Algorithm: subobjects/algorithm.md
      - Citation: subobjects/citation.md
      - Computational Forcefield: subobjects/computational_forcefield.md
      - Condition: subobjects/condition.md
      - Equipment: subobjects/equipment.md
      - Identifier: subobjects/identifier.md
      - Ingredient: subobjects/ingredient.md
      - Parameter: subobjects/parameter.md
      - Property: subobjects/property.md
      - Quantity: subobjects/quantity.md
      - Software Configuration: subobjects/software_configuration.md
  - API: api.md
  - Paginator: paginator.md
  - Exceptions: exceptions.md
  - FAQs: faqs.md

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: True
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
