site_name: CRIPT Python SDK

repo_url: https://github.com/C-Accel-CRIPT/cript
repo_name: C-Accel-CRIPT/cript

theme:
    name: material
    palette:
        primary: deep purple
        accent: deep purple
    icon:
        repo: fontawesome/brands/github

plugins:
    - search
    - mkdocs-jupyter
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                setup_commands:
                    - import sys
                    - sys.path.append("src")
                selection:
                    docstring_style: restructured-text

nav:
    - Home: index.md
    - Quickstart: quickstart.md
    - Tutorial: tutorial.md
    - Nodes:
        - Primary: nodes/primary.md
        - Secondary: nodes/secondary.md
    - API: api.md
    - Exceptions: exceptions.md

markdown_extensions:
    - toc:
        baselevel: 1
        permalink: True
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences