site_name: CRIPT Python SDK

repo_url: https://github.com/C-Accel-CRIPT/cript
repo_name: C-Accel-CRIPT/cript

nav:
  - Home: index.md
  - Tutorial:
    - Full Tutorial: tutorial/tutorial.md
    - Installation: tutorial/cript_installation.md
    - How to Get an API Token: tutorial/acquiring_api_token.md
  - Quick Start: quickstart.md
  - Nodes:
      - Collection: nodes/collection.md
      - Computation: nodes/computation.md
      - Computational Process: nodes/computational_process.md
      - Data: nodes/data.md
      - Experiment: nodes/experiment.md
      - Inventory: nodes/inventory.md
      - Material: nodes/material.md
      - Project: nodes/project.md
      - Process: nodes/process.md
      - Reference: nodes/reference.md
      - Software: nodes/software.md
  - Sub-objects:
      - Algorithm: subobjects/algorithm.md
      - Citation: subobjects/citation.md
      - Condition: subobjects/condition.md
      - Equipment: subobjects/equipment.md
      - Identifier: subobjects/identifier.md
      - Ingredient: subobjects/ingredient.md
      - Parameter: subobjects/parameter.md
      - Property: subobjects/property.md
      - Quantity: subobjects/quantity.md
      - Software Configuration: subobjects/software_configuration.md
  - Supporting Nodes: 
    - File: supporting_nodes/file.md
    - Group: supporting_nodes/group.md
    - User: supporting_nodes/user.md
  - API: api.md
  - Paginator: paginator.md
  - Exceptions: exceptions.md
  - FAQ: faq.md

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ src ]
          selection:
            docstring_style: sphinx
          options:
            show_bases: false
            show_source: false

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: True
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
