site_name: CRIPT SDK Documentation

theme: material

plugins:
    - search
    - mkdocs-jupyter
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    docstring_style: "restructured-text"
                rendering:
                    show_source: true
                    heading_level: 3

nav:
    - Home: index.md
    - Quickstart: quickstart.md
    - Tutorial: tutorial.md
    - Nodes:
        - Primary: nodes/primary.md
        - Secondary: nodes/secondary.md
    - API: api.md
    - Exceptions: exceptions.md

markdown_extensions:
    - toc:
        baselevel: 1
        permalink: True
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences