site_name: CRIPT Python SDK

repo_url: https://github.com/C-Accel-CRIPT/cript
repo_name: C-Accel-CRIPT/cript

theme:
  name: material
  logo: assets/images/CRIPT_full_logo_colored_transparent.png
  favicon: assets/images/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# This links the CRIPT logo to the CRIPT homepage
extra:
  homepage: https://criptapp.org

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_bases: false
            show_source: false
            docstring_style: sphinx

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tutorials:
      - Synthesis: tutorials/synthesis.md
      - Simulation: tutorials/simulation.md
  - Nodes:
      - Project: nodes/project.md
      - Collection: nodes/collection.md
      - Material: nodes/material.md
      - File: nodes/file.md
      - Experiment: nodes/experiment.md
      - Inventory: nodes/inventory.md
      - Process: nodes/process.md
      - ComputationalProcess: nodes/computational_process.md
      - Computation: nodes/computation.md
      - Data: nodes/data.md
      - Reference: nodes/reference.md
      - Software: nodes/software.md
      - User: nodes/user.md
      - Group: nodes/group.md
  - Subobjects:
      - Property: subobjects/property.md
      - Condition: subobjects/condition.md
      - Identifier: subobjects/identifier.md
      - Ingredient: subobjects/ingredient.md
      - Quantity: subobjects/quantity.md
      - Equipment: subobjects/equipment.md
      - SoftwareConfiguration: subobjects/software_configuration.md
      - Algorithm: subobjects/algorithm.md
      - Parameter: subobjects/parameter.md
      - Citation: subobjects/citation.md
  - API: api.md
  - Paginator: paginator.md
  - Exceptions: exceptions.md

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: True
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

