site_name: CRIPT SDK Documentation

theme: material

markdown_extensions:
- toc:
    baselevel: 1
    permalink: True

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    docstring_style: "restructured-text"
                rendering:
                    show_source: true
                    heading_level: 3