name: Install and Pytests

on:
  push:
    branches:
      - master
      - develop
      - trunk-merge/**
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.7, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependecies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install CRIPT Python SDK
        run: pip install .

      - name: Run pytest
        run: |
          pytest
