name: Install and Pytests

on:
  push:
    branches:
      - master
      - develop
      - trunk-merge/**
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        python-version: [3.9]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Install CRIPT Python SDK
        run: pip install .

      - name: Run pytest
        run: |
          python -m pytest
